baseURL = 'https://maiikiru.github.io/'
languageCode = 'en-us'
title = 'My New Hugo Site'
theme = 'hello-friend-ng'
paginate     = 10

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04"


  enableThemeToggle = true
  defaultTheme = "dark"

  # Subtitle for home
  homeSubtitle = "Welcome to my website"

  # Set disableReadOtherPosts to true in order to hide the links to other posts.
  disableReadOtherPosts = false

  # Enable sharing buttons, if you like
  enableSharingButtons = true

  # Metadata mostly used in document's head
  description = "My new Homepage"
  keywords = "homepage, blog"
  images = [""]

[author]
    name = "Mason Ho"

[taxonomies]
    category = "blog"
    tag      = "tags"
    series   = "series"

[languages]
  [languages.en]
    title = "Mason Ho"
    subtitle = "Welcome to my website"
    keywords = ""
    copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'
    readOtherPosts = "Read other posts"
    

    [languages.en.params.logo]
      logoText = "$ cd /home/"
      logoHomeLink = "/"
    # or
    #
    # path = "/img/your-example-logo.svg"
    # alt = "Your example logo alt text"

  # And you can even create generic menu
  [menu]
  [[menu.main]]
    identifier = "resume"
    name       = "Resume"
    url        = "/resume"


  [[params.social]]
    name = "github"
    url  = "https://github.com/Maiikiru"

  [[params.social]]
    name = "linkedin"
    url = "https://linkedin.com/in/masonh1"

  

  
